### ISSUE TITLE
user icon is not clickable

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#105]
**Is your feature request related to a problem? Please describe.**
Developer, Planner, Citizen is not clickable, only back and forth arrow are functional.

**Comment by Bachibouzouk** [comment]
@yelsre ask for the hover over feature to be removed, there was no click on feature enabled. Should it be enabled?

**Comment by catcad** [comment]
Yes, please.

**Comment by yelsre** [comment]
@Bachibouzouk the text in  the feedback was: "The change when clicking on "Planners" or "Citizens" happens _on hover_. --> This is a bit confusing so suggest to happen _on click_"

**Comment by Bachibouzouk** [comment]
@yelsre - sorry I apparently misremembered the feedback :( I linked the on click to the click on the arrow in my mind and thought the issue was closed.

**Comment by Bachibouzouk** [comment]
Related to #106
