### ISSUE TITLE
automated dynamic change of user possible?

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#106]
How difficult would it be to implement a dynamic change of the use?

**Comment by Bachibouzouk** [comment]
I am not sure of what you mean. You mean a user with login and password? Or you mean to land on a website tailored for each the the developper/planner/ctizen via URL ?

**Comment by catcad** [comment]
Nono, sorry for being unclear. They want it changing by itself every couple of seconds flipping though developer, planner, citizen, automattically. The critique was that the page looks and feels rather "static" because nothing moves on it. Only do if possible in reasonable time.

**Comment by Bachibouzouk** [comment]
It should be possible, although I am personally annoyed by things moving without my explicit click on websites, it make me think there are adds. I will set that with a lower prio

**Comment by Bachibouzouk** [comment]
Then should the user still be able to click on each user? Should the automatic motion start after some inactivity? Again, I find annoying when I read something and the banner updates to the next item before I have time to read everything. I don't have intuition for this so it would be easier for me to have given times of display in seconds :)

**Comment by catcad** [comment]
For now please make the change of the three option happening by either using the left and right arrow or by clicking on each icon. No automated motion yet. It this is still on the wishlist, then it goes in V2.

**Comment by Bachibouzouk** [comment]
It would be possible using https://www.w3schools.com/js/js_timing.asp
The question is, what would be the time interval?
