### ISSUE TITLE
Use our tools order of icons needs to be changed

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#117]
Mapping with OSM needs to be changed with On Grid mapping

**Comment by Bachibouzouk** [comment]
As there is already a card named "On Grid Mapping", do you mean you would like to swap their order ? 

Clockwise you would then have : "Cluster ...", "On Grid ...", "Mapping with OSM", "Survey ..." ?

**Comment by catcad** [comment]
Yes, sorry for being unclear. I meant switching On Grid with mapping with Mapping with OSM. So the bottom right needs to change position with the top right.
