### ISSUE TITLE
the year at the very bottom needs to be 2020

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#120]
can it be always the actual year? So it updates automatically to 2021 in 2021?
If difficult, a change to 2020 would be fine for now.

**Comment by Bachibouzouk** [comment]
Yes it can be, but does it make sense? I view it as a publication date for books, as long as the content is not updated, should the date be updated?

**Comment by catcad** [comment]
The idea is that the content with be updated constantly :)

**Comment by Bachibouzouk** [comment]
The text? Or the data?
