### ISSUE TITLE
Missing preview of map

### ISSUE THREAD

**Issue by christian-rli** [rl-institut/NESP2_website#143]
It was suggested to show a screenshot of the map. A click on it brings you there. 
Design suggestion: ![landing-page-map-div](https://user-images.githubusercontent.com/42000429/76945135-6b57f900-6902-11ea-87ec-c3a178106c2d.png)

Current screenshot for implementation:

![national_view](https://user-images.githubusercontent.com/42000429/76945222-81fe5000-6902-11ea-981b-67833d047a87.png)

@yelsre please confirm if the screenshot is ok to use before implementation. Also, feel free to post another one or say what changes need to be made before implementation.

**Comment by yelsre** [comment]
looks fine, thanks

**Comment by Bachibouzouk** [comment]
Duplicate of #137
