### ISSUE TITLE
Objective cards behave strange when screen size goes to medium

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#156]
![Screenshot from 2020-03-18 18-46-03](https://user-images.githubusercontent.com/4399407/76990757-c9a7ca80-6948-11ea-9bce-234ddf4cd087.png)

When I change the size of my window, this is what I get at some point. Interestingly, I don't have the same for the resource cards. Do you know what could be the difference?

_Originally posted by @Bachibouzouk in https://github.com/rl-institut/NESP2_website/pull/149#issuecomment-600773359_

**Comment by bmlancien** [comment]
I didn't take care of small and medium size screens, since I thought that desktop screens had priority. Should I fix this now?

**Comment by Bachibouzouk** [comment]
> I didn't take care of small and medium size screens, since I thought that desktop screens had priority. Should I fix this now?

If you can that would be great :)

For small the cards could go on top of each other for example, if that take too much time, just making them not be cut in half is already fine :)

**Comment by bmlancien** [comment]
Alright!
