### ISSUE TITLE
There is no "about" page

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#17]
The following text is to go on the “About” page, under “NESP”:

Nigerian Energy Support Programme (NESP) 
The Nigerian Energy Support Programme (NESP) is co-funded by the European Union and the German Government and is jointly implemented by Deutsche Gesellschaft für internationale Zusammenarbeit (GIZ) GmbH and the Federal Ministry of Power. It aims to foster private investments in the Nigerian Renewable Energy and Energy Efficiency Sector and to improve access to electricity for disadvantaged, rural communities.
The programme implements a multi-level approach by combining advisory on energy policy, economy and technical knowledge for a wide range of stakeholders. It is divided into three components: 
    • Electrification Planning and Data Management
    • Sustainable Energy Access (On-Grid & Off-Grid)
    • Enabling Environment for Renewable Energy and Energy Efficiency Investments

**Comment by Bachibouzouk** [comment]
@yelsre - this text is supposed to go in the "Our work" section or in the "Our team" section?
Here is a screenshot of the site design as I received it: 
![Bildschirmfoto_2019-11-11_17-30-47](https://user-images.githubusercontent.com/4399407/68603679-10704a00-04a9-11ea-895f-778f433b177e.png)

**Comment by yelsre** [comment]
@Bachibouzouk  this is the only text we received about NESP. So I would suggest to remove the sub-headings and just jump directly to this description. Then I think reduce the images to just 1. Do you have a placeholder image for this section or not?

Does this make sense?

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk this is the only text we received about NESP. So I would suggest to remove the sub-headings and just jump directly to this description. Then I think reduce the images to just 1. Do you have a placeholder image for this section or not?

I just used a grey image as placeholder

> Does this make sense?

Yes :)
