### ISSUE TITLE
Navigation bar design is not matching goal

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#2]
The header bar should be sticky always at the top of the page, even when one scrolls down

- [x] Check also the image stretch (#56)

- [ ] behavior of the nav bar for smartphones

**Comment by Bachibouzouk** [comment]
I am not sure of what should be the behavior of the nav bar for smartphones? Do you have suggestion @bmlancien ?

**Comment by bmlancien** [comment]
@Bachibouzouk after merging the new dev local branch into feature/nav, the LP looks different. You had this problem too, right?

![Bildschirmfoto vom 2019-11-26 11-33-55](https://user-images.githubusercontent.com/33999424/69622152-b2af3680-1040-11ea-9a0d-9f6e24ace328.png)

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk after merging the new dev local branch into feature/nav, the LP looks different. You had this problem too, right?
> 
> ![Bildschirmfoto vom 2019-11-26 11-33-55](https://user-images.githubusercontent.com/33999424/69622152-b2af3680-1040-11ea-9a0d-9f6e24ace328.png)

Yes it is due to app.css not loading (if you can download the minimum foundation package we need we can have it locally instead of loading as external css)

**Comment by Bachibouzouk** [comment]
@bmlancien with the latest `dev` you should not have this problem anymore :)
