### ISSUE TITLE
Missing texts and images

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#35]
## Landing page
- [x] text Welcome to Nigeria

### Features
- [x] Image Features for Citizen
- [x]  Text Features for Citizen

### Stay in touch
- [x] link twitter (#74)
- [x] link instagram (#74)
- [x] link youtube (#74)

### Contact
- [x] phone number

## Extra page accessible from links in the footer
- [x] Text Terms of service
- [x] Text Privacy Policy

## Resources page
- [x] link "About our Resources" should point where?
- [x] link "Methodology" should point where?
- [x] link "Get involved" should point where?
- [x] descriptions for each of the 4 resources
- [x] link "Go to resource" (below each resource description) should point where?

## About page
- [x] text About this platform
- [x] text in small descriptions panels
- [x] image Nigeria SE4All agenda
- [x] image SE4All 30:30:30
- [x] text Nigeria SE4All agenda
- [x] text Nigeria SE4All 30:30:30
- [x] text FMP (mandate + mission + vision)
- [x] image for NESP
- [x] text for stakeholders
- [x] images stakeholders

**Comment by Bachibouzouk** [comment]
@catcad , @yelsre - do you have more information about these texts and images?

**Comment by yelsre** [comment]
@Bachibouzouk  - GIZ are working on collecting it. Deadline for internal collection is 22/11/2019

**Comment by Bachibouzouk** [comment]
> @Bachibouzouk - GIZ are working on collecting it. Deadline for internal collection is 22/11/2019

ok perfect :)

**Comment by yelsre** [comment]
Text for stakeholders

Change sub-headings and links to be the following:

Rural Electrification Agency (REA)
-> https://rea.gov.ng/

Nigeria Electricity Regulatory Commission (NERC)
-> https://nerc.gov.ng/

Transmission Company of Nigeria (TCN)
->https://tcn.org.ng/

**Comment by catcad** [comment]
For the photos please correct them to your best knowledge (turning, cropping, color and contrast).
Photo Landing Page and FMP:
![DSC_0085](https://user-images.githubusercontent.com/33006916/69797846-b376d280-11d0-11ea-9a08-d9d2b078c58d.JPG)
FMP additional two:
![DSC_1445](https://user-images.githubusercontent.com/33006916/69798068-0781b700-11d1-11ea-9a7c-c7afe7c1f83e.JPG)
![DSC_0265](https://user-images.githubusercontent.com/33006916/69798079-0badd480-11d1-11ea-8c0c-8302f7b788b1.JPG)
Photo NESP:
![01 (19)](https://user-images.githubusercontent.com/33006916/69798120-1ec0a480-11d1-11ea-93ab-d24b1992f987.JPG)

**Comment by catcad** [comment]
FMP Text:

> The Ministry of Power’s role is to formulate and implement the policies of Federal Government of Nigeria (FGN) for the development and efficient operation of the Nigerian Electricity Supply Industry (NESI). The aims of the Ministry’s Policies are as stated in the Electric Power sector Reform Act 2005:
- a.	To maximize access to electricity services, by promoting and facilitating consumer connection to distribution systems in both rural and urban areas;
- b.	To ensure that an adequate supply of electricity is available to consumers;
- c.	To ensure that the prices charged by licensees are fair to consumers and are sufficient to allow the licensees to finance their activities and allow for reasonable earning for efficient operation;
- d.	To ensure the safety, security, reliability and quality of service in the production and delivery of electricity to consumers

**Comment by catcad** [comment]
FMP additional text:

Vision:  To be a key enabler of community and economic growth by facilitating delivery of functional, affordable and reliable power infrastructure assets and associated services.

Mission:  Expedite National Development by providing policies, systems and structures which ensure the delivery of reliable, functional and cost effective power infrastructure assets and services that meet the needs of all.

 Mandate:  Initiate and coordinate policies and strategies for the sustainable development of reliable, robust and affordable power supply.

**Comment by catcad** [comment]
Information on logo size and ratio:

Please find GIZ's comments on the website below: 

1.	The GIZ logo looks quite small in comparison to the EU flag and the German Cooperation logo. Could you please check if the size is correct according to the GIZ guidelines. (attached in PPT). 
I have the feeling that it has to be slightly increased. 
2.	Please use the full name for FMP and NESP in the About section. Additionally I included a short description for the NESP box (see PPT attached).
3.	I also agree with Oliver, the section Maps is more important than the About section. 

If you have questions on this or if you need further information from my side please let me know. 

Regards, 
Melanie


[Changes on Website.pptx](https://github.com/rl-institut/NESP2_website/files/3901169/Changes.on.Website.pptx)

**Comment by Bachibouzouk** [comment]
>     1. The GIZ logo looks quite small in comparison to the EU flag and the German Cooperation logo. Could you please check if the size is correct according to the GIZ guidelines. (attached in PPT).
>        I have the feeling that it has to be slightly increased

I find the guideline are not clearly defined as I pointed [here](https://github.com/rl-institut/NESP2_website/issues/45#issuecomment-558995257)

**Comment by yelsre** [comment]
> > ```
> > 1. The GIZ logo looks quite small in comparison to the EU flag and the German Cooperation logo. Could you please check if the size is correct according to the GIZ guidelines. (attached in PPT).
> >    I have the feeling that it has to be slightly increased
> > ```
> 
> I find the guideline are not clearly defined as I pointed [here](https://github.com/rl-institut/NESP2_website/issues/45#issuecomment-558995257)

I replied on this issue

**Comment by yelsre** [comment]
> FMP additional text:
> 
> Vision: To be a key enabler of community and economic growth by facilitating delivery of functional, affordable and reliable power infrastructure assets and associated services.
> 
> Mission: Expedite National Development by providing policies, systems and structures which ensure the delivery of reliable, functional and cost effective power infrastructure assets and services that meet the needs of all.
> 
> Mandate: Initiate and coordinate policies and strategies for the sustainable development of reliable, robust and affordable power supply.

@Bachibouzouk , note that the order here has changed from the original. This order here (Vision -> Mission -> Mandate) is the correct order.

**Comment by bmlancien** [comment]
I've cropped the first two ones. The other two pictures just have a slighter higher contrast.

![nesp_1](https://user-images.githubusercontent.com/33999424/69824721-0b332f00-120d-11ea-8394-c0b7d202c09c.png)
![nesp_2](https://user-images.githubusercontent.com/33999424/69824732-0f5f4c80-120d-11ea-8b35-8a179a27438b.png)
![nesp_3](https://user-images.githubusercontent.com/33999424/69824741-12f2d380-120d-11ea-98bf-87671ce98ff3.png)
![nesp_4](https://user-images.githubusercontent.com/33999424/69824746-171ef100-120d-11ea-83e0-3f73fa91d713.png)

**Comment by Bachibouzouk** [comment]
> FMP Text:
> 
> > The Ministry of Power’s role is to formulate and implement the policies of Federal Government of Nigeria (FGN) for the development and efficient operation of the Nigerian Electricity Supply Industry (NESI). The aims of the Ministry’s Policies are as stated in the Electric Power sector Reform Act 2005:
> 
>     * a.	To maximize access to electricity services, by promoting and facilitating consumer connection to distribution systems in both rural and urban areas;
> 
>     * b.	To ensure that an adequate supply of electricity is available to consumers;
> 
>     * c.	To ensure that the prices charged by licensees are fair to consumers and are sufficient to allow the licensees to finance their activities and allow for reasonable earning for efficient operation;
> 
>     * d.	To ensure the safety, security, reliability and quality of service in the production and delivery of electricity to consumers

In the design sent by Alzino, there was only texts for Vision, Mission, Mandate. Where is this text supposed to be inserted ?

**Comment by Bachibouzouk** [comment]
@yelsre , @catcad - do you have more texts?

**Comment by yelsre** [comment]
> @yelsre , @catcad - do you have more texts?

Mapping with OSM
------------------------
Data on the Open Street Map (OSM) platform is utilised for off-grid areas in this project. This is detailed data of building outlines and any other geospatial datasets, generated either from on-site knowledge or from high resolution satellite imagery. If an Off-grid area is not currently on the OSM database, it can be easily added.
Do you have an area of interest for an electrification project that you want to do further assessment on? Or do you want to contribute to data to assist electrification efforts in Nigeria? Check out the OSM tools below to help you get started:

- 	Create an OSM account on [openstreetmap.org](https://www.openstreetmap.org/).
-	Read the beginner’s guide on [learnosm.org](https://learnosm.org/en/) for an introduction.
-	[JOSM](https://josm.openstreetmap.de/) is a desktop application in which you can map areas of interest.
-	The [HOT Tasking Manager](https://tasks.hotosm.org/) is used to manage tasks of areas to map. Get in touch and send us your OSM username if you want to be involved.

Survey Tools
----------------
Once a remote assessment of the satellite imagery has taken place, it is normally required that a potential location for electrification is visited and surveyed. Here more detailed information is collected to enable a more accurate demand assessment for the purposes of electrification. At Nigeria SE4ALL we have developed survey templates and tools to conduct the surveys. 
Do you want to survey a potential location for electrification purposes? Or do you live in a settlement that you think could benefit from an electrification project, and want to share more information on this location to facilitate a project to happen? Check out the survey tools below to get started:

- 	To gather geospatial data about business locations, have a look at using [Field Papers](http://fieldpapers.org/) in conjunction with OSM data.
- 	A [KoBoToolbox](kobotoolbox.org) questionnaire is also available. Get in touch with us and describe in a few sentences why you would like to collect the data, as well as sharing your KoBoToolbox username. You can then receive access to the questionnaires.

Images
-----------
Can we replace the image for "Mapping with OSM" to the following:
![Mapping-with-OSM-3](https://user-images.githubusercontent.com/51226492/72253597-3679ae00-3602-11ea-9cba-93eae450366a.png)
@catcad  maybe you have a nice image for the Cluster methodology?

**Comment by Bachibouzouk** [comment]
Thanks @yelsre, I updated the website

**Comment by yelsre** [comment]
Content for the grid tracking section (under tools > on-grid mapping)

# On Grid Mapping
How can I track the grid?

The Medium Voltage (MV) grid data used by Nigeria SE4ALL is either primary data which is gathered first hand by the SE4ALL field team, or secondary data whose quality has been validated by the SE4ALL field team. Our aim is to maintain the most comprehensive grid data-set for Nigeria. To achieve this, we encourage anyone who may have more up-to date grid data, or additions to the grid data-set generated to get in touch and share their updates.

**Comment by catcad** [comment]
Text for Welcome:

The Sustainable Energy for All Initiative is a multi-stakeholder partnership between governments, the private sector, and civil society. Launched by the UN Secretary-General in 2011, it has three interlinked objectives to be achieved by 2030: ensuring universal access to modern energy services, doubling the global rate of improvement in energy efficiency and doubling the share of renewable energy in the global energy mix.
 
Nigeria SE4ALL portal seeks to showcase and track Nigeria's actions and activities toward the achievements of Sustainable Development Goal 7 (SDG7), which calls for universal access to sustainable energy by 2030, and the Paris Agreement, which calls for reducing greenhouse gas emissions to limit climate warming to below 2° Celsius.
 
The portal also hosts the Federal Ministry of Power sophisticated electrification planning platform which holds the most accurate and ground-truthed data about electricity status in the country. The portal provides invaluable data for government, investors and developers.

**Comment by catcad** [comment]
Text for the About section:

The SE4All Action Agenda for Nigeria has been developed in line with the guiding principles contained in the Guidelines for Developing National Sustainable Energy for All Action Agendas in Africa that were developed by African stakeholders, notably: 
(i)	Building on existing plans/programmes/strategies; 
(ii)	Political commitment and leadership; 
(iii)	A balanced and integrated approach; 
(iv)	An inter-ministerial and cross-sectoral approach; 
(v)	Adherence to sustainable development principles; 
(vi)	Participation and meaningful involvement of all stakeholders; 
(vii)	Gender equality and inclusiveness; and 
(viii)	Transparency and accountability. 
The Federal Government of Nigeria has shown strong commitment in accelerating Nigeria's SE4All Action Plan, and integrating the same within the broader policy framework, notably Vision 20:2020, which provides the main framework for national development. SE4All builds on these foundations to look at additional strategic issues that will need to be addressed to meet the long-term challenges in the energy sector. The Federal Ministry of Power is the designate focal point institution (FPI) for the overall coordination of SE4All activities in Nigeria, while the SE4All focal point person (FPP) appointed by the ministry will be responsible for liaison, stakeholder consultation, review, monitoring and reporting of progress among all stakeholders in the Nigerian SE4All action agenda implementation and coordination process.

**Comment by catcad** [comment]
Text in small description panel:

Nigeria SE4All & 30:30:30:
Nigeria's SE4All Action Agenda takes a leading role in supporting the implementation of SDG goals in particular SDG7 in the country, and to monitor and report on progress towards the Goal.

Federal Ministry of Power (FMP):
The Federal Ministry of Power is the policy-making arm of the Federal Government with the responsibility for the provision of power in the country. 

Stakeholders:
The Nigeria Electricity Supply Industry (NESI) has various stakeholders, these are some of the key industry participants.

**Comment by catcad** [comment]
Image for Nigeria SE4All section
![grafik](https://user-images.githubusercontent.com/33006916/75268277-99f91d00-57f7-11ea-9850-9733b6625368.png)

**Comment by catcad** [comment]
Text for About page / Stakeholder section at the bottom the text for Nigeria Electricity Regulatory Commission (NERC):

The Commission was created by and performs its operations based on the guidelines as stipulated in the Electric Power Sector Reform Act 2005. 
The mission is to promote and ensure an investor-friendly industry and efficient market structure to meet the needs of Nigeria for safe, adequate, reliable and affordable electricity.

Logo update (only logo no text): 
![grafik](https://user-images.githubusercontent.com/33006916/75379134-275e6f00-58d5-11ea-91e8-107d307467e1.png)

**Comment by catcad** [comment]
Here is the small text for the stakeholder REA:

The Rural Electrification Agency is mandated by the Federal Government to facilitate its goals and targets to increase access to electricity to 75% and 90% by 2020 and 2030 respectively and at least 10% of renewable energy mix by 2025.
REA is mandated to promote rapid, safe, clean energy and cost-effective expansion of electricity access in unelectrified rural areas across Nigeria with economic development objectives. The electrification of the rural areas would also help improve the livelihood and socio-economic conditions of rural dwellers.
