### ISSUE TITLE
Edit the proportions of GIZ logos

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#45]
**Submitted by:** GIZ - Melanie
**Relevant section:** Footer
**Description of issue:**
The GIZ logo looks quite small in comparison to the EU flag and the German Cooperation logo. Could you please check if the size is correct according to the GIZ guidelines. (attached).

**Attach screenshot or email**
![grafik](https://user-images.githubusercontent.com/33006916/69342751-85dbd780-0c6c-11ea-9fbc-aae2ba8fe535.png)
![grafik](https://user-images.githubusercontent.com/33006916/69342764-8d02e580-0c6c-11ea-897f-be89b5768241.png)

**Add "assigned by..." Label**

**Comment by Bachibouzouk** [comment]
@yelsre , @catcad  -The GIZ Guidelines are not very clear, is there a version with precise grid lines and where the important dimensions are shown with arrows?

Here is an example of what I mean by clearly indicated dimensions :
![example_grid](https://user-images.githubusercontent.com/4399407/69709012-e3ed3c80-10fc-11ea-9188-3034368b99a7.png)

**Comment by yelsre** [comment]
I agree, it is not clear. I played with this "80%" point, and the attached photo is the only way I could get it to work. This also seems to somehow match the original picture.
![image](https://user-images.githubusercontent.com/51226492/69802092-166c6780-11d9-11ea-85ed-2c5c0cafde57.png)

**Comment by Bachibouzouk** [comment]
@yelsre Thank you this is much clearer that way! You could give it to GIZ so they can make their requirements better for future users :)
