### ISSUE TITLE
Nigerian crest is "stretched" in chrome browser

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#46]
**Submitted by:** INT
**Relevant section:** Menu bar
**Description of issue:**
The Nigerian crest is not the correct proportions. This is only occurring in the Chrome browser.

**Attach screenshot or email**
![grafik](https://user-images.githubusercontent.com/33006916/69342887-c50a2880-0c6c-11ea-8904-395764a4c7e2.png)

**Add "assigned by..." Label**

**Comment by catcad** [comment]
This problem only occurs in chrome - not in firefox.

**Comment by Bachibouzouk** [comment]
Closed by #54
