### ISSUE TITLE
Cards on About page don't have the same height

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NESP2_website#61]
## Description of the problem
Data-equalizer is not working as it should. Every card should have the same height independently from their content.

**Comment by Bachibouzouk** [comment]
Can you provide a screenshot of the problem ?

**Comment by bmlancien** [comment]
![Bildschirmfoto vom 2019-11-28 11-33-40](https://user-images.githubusercontent.com/33999424/69799196-179a9600-11d3-11ea-97df-5267dec5447a.png)

The problem is that NESP card doesn't have the same size as the other

**Comment by Bachibouzouk** [comment]
This is likely due to a lack of js from foundation :) I will add the js files
