### ISSUE TITLE
Menu bar: fonts and symbols are too big and Nigeria se4all needs to be capitalised

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#63]
**Submitted by:** Frankie and Catherina
**Relevant section:** Menu bar
**Description of issue:**
The proportions of the menu bar compared to the rest of the page are larger in the implemented site, than compared to the website mock-up from Alsino.

The text "Nigeria Se4all" on the left hand side of the menu bar should be capitalised, as in the mockup.

**Attach screenshot or email**
**Add "assigned by..." Label**

**Comment by Bachibouzouk** [comment]
Closed via #66
