### ISSUE TITLE
Browsers such as IE and Safari were not tested yet

### ISSUE THREAD

**Issue by bmlancien** [rl-institut/NESP2_website#64]
## Description of the problem
Test with following browsers:

- [ ] IE
- [ ] Safari
- [ ] Opera (lower priority because it is not used by many people)

**Comment by catcad** [comment]
On a smaller laptop screen (using chrome) the “Learn more” button overlaps with the Welcome title
![grafik](https://user-images.githubusercontent.com/33006916/73439576-1e1ec880-4350-11ea-8850-4607351716d3.png)

**Comment by Bachibouzouk** [comment]
Do you know what to do for that @bmlancien ?
