### ISSUE TITLE
"Learn more" button - issue

### ISSUE THREAD

**Issue by yelsre** [rl-institut/NESP2_website#84]
## Description of the problem

The learn more button overlaps with the heading text on Chrome in smaller window sizes.

![learn more button - issue](https://user-images.githubusercontent.com/51226492/73928364-4029c500-48d3-11ea-893e-dab87f039ab7.jpg)

**Comment by Bachibouzouk** [comment]
@yelsre, @bmlancien should have fixed the problem, can you try again?

**Comment by yelsre** [comment]
Hi, yep looks better now. Thanks!
