### ISSUE TITLE
Our progress in numbers elements are not connected to database

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#89]
## Description of the problem

Some of the numbers from "Our progress in numbers" section are not linked to the data server

- [x] village remotely mapped
- [x] buildings mapped

**Comment by Bachibouzouk** [comment]
@yelsre do you have the SQL commands?

**Comment by Bachibouzouk** [comment]
@yelsre, is the total number of mapped buildings in the `se4all.osm_building` ?

**Comment by yelsre** [comment]
> @yelsre, is the total number of mapped buildings in the `se4all.osm_building` ?

@Bachibouzouk no, that is *all* osm buildings in Nigeria

> @yelsre do you have the SQL commands?

Yes, I have created views for you: 
web.ourprogress_buildingsmapped_value_v
web.ourprogress_kmelectricitygridtracked_value_v
web.ourprogress_villagesremotelymapped_value_v

Actually we get the buildings mapped value from [here](http://www.missingmaps.org/leaderboards/#/tm-project-6048), if you can easily find a way reflect that building count value.

**Comment by Bachibouzouk** [comment]
could the `ourprogress_villagesremotelymapped_id` column of the `web.ourprogress_villagesremotelymapped`be named simply `id` ?

**Comment by yelsre** [comment]
> could the `ourprogress_villagesremotelymapped_id` column of the `web.ourprogress_villagesremotelymapped`be named simply `id` ?

Does it affect anything? All id columns follow that naming convention.

**Comment by Bachibouzouk** [comment]
No it does not affect anything, just my understanding of the logic behind this naming convention as the colum is linked to the table, I don't see the advantage in repeating the name of the table in the column names, i.e. `ourprogress_villagesremotelymapped.ourprogress_villagesremotelymapped_id` instead of `ourprogress_villagesremotelymapped.id`which carry the same information and is more concise

**Comment by Bachibouzouk** [comment]
@yelsre  There are 432915 villages which exceed the max limit of 2870 and only one building, are the numbers in the table switched maybe?

**Comment by yelsre** [comment]
> No it does not affect anything, just my understanding of the logic behind this naming convention as the colum is linked to the table, I don't see the advantage in repeating the name of the table in the column names, i.e. `ourprogress_villagesremotelymapped.ourprogress_villagesremotelymapped_id` instead of `ourprogress_villagesremotelymapped.id`which carry the same information and is more concise

Indeed it is a matter of preference. Explicitly naming has some advantages too.
https://stackoverflow.com/questions/2749995/the-right-way-to-write-id-in-columns-in-sql

**Comment by yelsre** [comment]
> @yelsre There are 432915 villages which exceed the max limit of 2870 and only one building, are the numbers in the table switched maybe?

I am not sure where you get these values from? I have attached all 3 select statements as a screenshot and their resultant data type, so it is clear what I am seeing. 
![image](https://user-images.githubusercontent.com/51226492/74514938-da11f300-4f0d-11ea-91d5-38b6fae54eee.png)
![image](https://user-images.githubusercontent.com/51226492/74514958-e1d19780-4f0d-11ea-92d5-9b1f8b3718fd.png)
![image](https://user-images.githubusercontent.com/51226492/74514976-ebf39600-4f0d-11ea-85b4-4ad05b25f129.png)

**Comment by Bachibouzouk** [comment]
> Indeed it is a matter of preference. Explicitly naming has some advantages too.
> https://stackoverflow.com/questions/2749995/the-right-way-to-write-id-in-columns-in-sql

Thanks for the link, indeed for merging tables it has its advantages

**Comment by Bachibouzouk** [comment]
> I am not sure where you get these values from?

I was getting them from the table `ourprogress_villagesremotelymapped` by summing the number of rows and not from the views, this is probably why :)
