### ISSUE TITLE
The maximal values of "Our progress in numbers" are arbitrary

### ISSUE THREAD

**Issue by Bachibouzouk** [rl-institut/NESP2_website#90]
## Description of the problem

Mapping to number to a progression circle, require a maximal value of the number (for full circle)
The maximal number for each of the following categories is required :

- [x] km electricity
grid tracked

- [x] village remotely mapped

- [x] buildings mapped

**Comment by Bachibouzouk** [comment]
@yelsre - do you have inputs?

**Comment by yelsre** [comment]
@Bachibouzouk  there is a table - "web.ourprogress_maximums" on the database with the values there. Could you also change "village remotely mapped" to "villages remotely mapped" please? Thanks

**Comment by Bachibouzouk** [comment]
> Could you also change "village remotely mapped" to "villages remotely mapped" please?

Did it in 1d89260b50c982cd091f596e2cdac30b6b344eac
