### ISSUE TITLE
Request: Width of the outer green circle for "progress in numbers"

### ISSUE THREAD

**Issue by catcad** [rl-institut/NESP2_website#94]
## Description of the problem
Can the circle been widend a bit to increase its visibility easily?
If yes, then please implement accordingly.
Thanks

**Comment by Bachibouzouk** [comment]
@catcad yes it is possible, I would also like to know the max number --> #90 I should input

Just to be sure: the radius of the circle should be bigger or the thickness of the line should be increased?
